# Generated by Django 4.2.3 on 2023-08-01 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_body', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOpeningForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('mail_id', models.EmailField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('material1', models.BooleanField()),
                ('material2', models.BooleanField()),
                ('material3', models.BooleanField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_body.accounttype')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_body.branch')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_body.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
