# Generated by Django 4.2.3 on 2023-08-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_body', '0002_accountopeningform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountopeningform',
            name='material1',
        ),
        migrations.RemoveField(
            model_name='accountopeningform',
            name='material2',
        ),
        migrations.RemoveField(
            model_name='accountopeningform',
            name='material3',
        ),
        migrations.AddField(
            model_name='accountopeningform',
            name='chequebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountopeningform',
            name='credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountopeningform',
            name='debit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountopeningform',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
