# Generated by Django 4.2.3 on 2023-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_body', '0003_remove_accountopeningform_material1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountopeningform',
            name='address',
            field=models.TextField(max_length=250),
        ),
    ]
