# Generated by Django 4.2.3 on 2023-08-03 10:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bank_body', '0004_alter_accountopeningform_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountopeningform',
            name='chequebook',
        ),
        migrations.RemoveField(
            model_name='accountopeningform',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='accountopeningform',
            name='debit_card',
        ),
        migrations.AddField(
            model_name='accountopeningform',
            name='materials_required',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('debitcard', 'Debit card'), ('creditcard', 'Credit card'), ('chequebook', 'Cheque book')], default='empty', max_length=20),
        ),
    ]
